/**
 * Lisa's Angry Initiative - Validation Script
 * @module validate
 * @author Lisa's Dungeon
 * @license Proprietary
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');

function validateModule() {
  const packageJson = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8'));
  const moduleJson = JSON.parse(fs.readFileSync(path.join(projectRoot, 'module.json'), 'utf8'));

  const errors = [];

  if (packageJson.version !== moduleJson.version) {
    errors.push(`Version mismatch: package.json (${packageJson.version}) vs module.json (${moduleJson.version})`);
  }

  const requiredFiles = [
    'package.json',
    'module.json',
    'LICENSE',
    'README.md',
    'CHANGELOG.md',
    'scripts/lisas-angry-initiative.js',
    'scripts/main.js',
    'scripts/lisas-angry-initiative-class.js',
    'scripts/constants.js',
    'scripts/recovery.js',
    'scripts/phase-variants.js',
    'scripts/custom-recovery-tables.js',
    'scripts/integration-hooks.js',
    'scripts/phase-indicators.js',
  ];

  for (const file of requiredFiles) {
    if (!fs.existsSync(path.join(projectRoot, file))) {
      errors.push(`Missing required file: ${file}`);
    }
  }

  const scriptContent = fs.readFileSync(path.join(projectRoot, 'scripts/main.js'), 'utf8');
  const forbiddenPatterns = [/claude/i, /chatgpt/i, /ai-assisted/i, /generated by/i, /anthropic/i];

  for (const pattern of forbiddenPatterns) {
    if (pattern.test(scriptContent)) {
      errors.push(`Found forbidden pattern in main.js: ${pattern}`);
    }
  }

  if (errors.length > 0) {
    console.error('Validation failed:');
    errors.forEach(e => console.error(`  - ${e}`));
    process.exit(1);
  }

  console.log(`Validation passed for lisas-angry-initiative ${packageJson.version}`);
}

validateModule();
